version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: /bin/sh -c "./../wait-for/wait-for -t 240 db:5432 -- echo 'Postgres is up' && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - "db"
      - "rabbitmq"
    image: fettay/resto_web
  rabbitmq:
          image: "rabbitmq:3"
  worker:
    build: .
    command: /bin/sh -c "./../wait-for/wait-for -t 240 db:5432 -- echo 'Postgres is up' && celery -A resto_server worker -l info"
    depends_on:
      - "db"
      - "rabbitmq"
    image: fettay/resto_worker
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always