# Generated by Django 3.0.3 on 2020-06-10 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('restaurant', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
