# Generated by Django 3.0.3 on 2020-06-17 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200616_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Order'),
        ),
    ]
