# Generated by Django 3.0.3 on 2020-06-17 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20200617_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='meal',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Order'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together={('owner', 'provider')},
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('owner', 'resto_id', 'provider')},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='restaurant',
        ),
    ]
